### ISSUE TITLE
Stratis comands last 2 lines (destorying filesystem )

### ISSUE THREAD

**Issue by firasbenhmida** [halekammoun/RHCSA-Training#2]
Hi,
stratis filesystem destroy name_pool name_filesystem → pour supprimer le filesystem.

You also need to delete the snapshot : ----> 

```stratis filesystem destroy name_pool  name_snapshot
stratis filesystem destroy name_pool  name_filesystem
```

**Comment by halekammoun** [comment]
Hello!
Yes, we did that during the training, but I forgot to document it, thanks a lot! 😊
